import { VscChromeMinimize, VscChromeMaximize, VscChromeClose } from "react-icons/vsc";

export const rightCornerButtons = [
  {
    title: "minimize",
    icon: <VscChromeMinimize />,
  },
  {
    title: "maximize",
    icon: <VscChromeMaximize />,
  },
  {
    title: "close",
    icon: <VscChromeClose />,
  },
];

export const helpMenuItems = [
  { type: "item", label: "Welcome" },
  { type: "item", label: "Show All Commands", shortcut: "Ctrl+Shift+P" },
  { type: "item", label: "Documentation" },
  { type: "item", label: "Editor Playground" },
  { type: "item", label: "Show Release Notes" },
  { type: "separator" },
  { type: "item", label: "Keyboard Shortcuts Reference", shortcut: "Ctrl+K Ctrl+R" },
  { type: "item", label: "Video Tutortials" },
  { type: "item", label: "Tips and Tricks" },
  { type: "separator" },
  { type: "item", label: "Join us on Twitter" },
  { type: "item", label: "Video Tutorials" },
  { type: "item", label: "Report Issue" },
  { type: "separator" },
  { type: "item", label: "View License" },
  { type: "item", label: "Privacy Statement" },
  { type: "separator" },
  { type: "item", label: "Toggle Developer Tools" },
  { type: "item", label: "Open Process Explorer" },
  { type: "separator" },
  { type: "item", label: "Check for Updates" },
  { type: "separator" },
  { type: "item", label: "About" },
];

export const runMenuItems = [
  { type: "item", label: "Start Debugging", shortcut: "F5" },
  { type: "item", label: "Run Without Debugging", shortcut: "Ctrl+F5" },
  { type: "item", label: "Stop Debugging", shortcut: "Shift+F5" },
  { type: "item", label: "Restart Debugging", shortcut: "Ctrl+Shift+F5" },
  { type: "separator" },
  { type: "item", label: "Open Configurations" },
  { type: "item", label: "Add Configurations..." },
  { type: "separator" },
  { type: "item", label: "Step Over", shortcut: "F10" },
  { type: "item", label: "Step into", shortcut: "F11" },
  { type: "item", label: "Step Out", shortcut: "Shift+F11" },
  { type: "item", label: "Continue", shortcut: "F5" },
  { type: "separator" },
  { type: "item", label: "Toggle Breakpoint", shortcut: "F9" },
  { type: "item", label: "New Breakpoint" },
  { type: "separator" },
  { type: "item", label: "Enable All Breakpoints" },
  { type: "item", label: "Disable All Breakpoints" },
  { type: "separator" },
  { type: "item", label: "Remove All Breakpoints" },
  { type: "separator" },
  { type: "item", label: "Install Additional Debuggers..." },
];

export const goMenuItems = [
  { type: "item", label: "Back", shortcut: "Alt+LeftArrow" },
  { type: "item", label: "Forward", shortcut: "Alt+RightArrow" },
  { type: "item", label: "Last Edit Location", shortcut: "Ctrl+K Ctrl+Q" },
  { type: "separator" },
  { type: "item", label: "Switch Editor" },
  { type: "item", label: "Switch Group" },
  { type: "separator" },
  { type: "item", label: "Go to File...", shortcut: "Ctrl+P" },
  { type: "item", label: "Go to Symbol in Workspace...", shortcut: "Ctrl+T" },
  { type: "separator" },
  { type: "item", label: "Go to Symbol in Editor", shortcut: "Ctrl+Shift+O" },
  { type: "item", label: "Go to Definition", shortcut: "F12" },
  { type: "item", label: "Go to Declaration" },
  { type: "item", label: "Go to Type Definition" },
  { type: "item", label: "Go to Implementations", shortcut: "Ctrl+F12" },
  { type: "item", label: "Go to References", shortcut: "Shift+F12" },
  { type: "separator" },
  { type: "item", label: "Go to Line/column...", shortcut: "Ctrl+F1G" },
  { type: "item", label: "Go to Bracket", shortcut: "Shift+F12" },
  { type: "separator" },
  { type: "item", label: "Next Problem", shortcut: "Ctrl+Shift+\\" },
  { type: "item", label: "Previous Problem", shortcut: "Shift+F8" },
  { type: "separator" },
  { type: "item", label: "Next Change", shortcut: "Alt+F3" },
  { type: "item", label: "Previous Change", shortcut: "Shift+Alt+F3" },
];

export const viewMenuItems = [
  { type: "item", label: "Command Palette...", shortcut: "Ctrl+Shift+P" },
  { type: "item", label: "Open View..." },
  { type: "separator" },
  { type: "item", label: "Apperance" },
  { type: "item", label: "Editor Layout" },
  { type: "separator" },
  { type: "item", label: "Explorer", shortcut: "Ctrl+Shift+E" },
  { type: "item", label: "Search", shortcut: "Ctrl+Shift+F" },
  { type: "item", label: "Source Control", shortcut: "Ctrl+Shift+G" },
  { type: "item", label: "Run", shortcut: "Ctrl+Shift+D" },
  { type: "item", label: "Extensions", shortcut: "Ctrl+Shift+X" },
  { type: "item", label: "Testing" },
  { type: "separator" },
  { type: "item", label: "Problems", shortcut: "Ctrl+Shift+M" },
  { type: "item", label: "Output", shortcut: "Ctrl+Shift+U" },
  { type: "item", label: "Debug Console", shortcut: "Ctrl+Shift+Y" },
  { type: "item", label: "Terminal", shortcut: "Ctrl+`" },
  { type: "separator" },
  { type: "item", label: "Word Wrap", shortcut: "Alt+Z" },
  { type: "item", label: "Sticky Scroll" },
];

export const terminalMenuItems = [
  { type: "item", label: "New Terminal", shortcut: "Ctrl+Shift+`" },
  { type: "item", label: "Split Terminal", shortcut: "Ctrl+Shift+5" },
  { type: "separator" },
  { type: "item", label: "Run Task" },
  { type: "item", label: "Run Build Task", shortcut: "Ctrl+Shift+8" },
  { type: "item", label: "Run Active File" },
  { type: "item", label: "Run Selected Text" },
  { type: "separator" },
  { type: "item", label: "Show Running Tasks..." },
  { type: "item", label: "Restart Running Tasks..." },
  { type: "item", label: "Terminate Task.." },
  { type: "separator" },
  { type: "item", label: "Configure Tasks..." },
  { type: "item", label: "Configure Default Build Task..." },
];

export const selectionMenuItems = [
  { type: "item", label: "Select All", shortcut: "Ctrl+A" },
  { type: "item", label: "Expand Selection", shortcut: "Shift+Alt+RightArrow" },
  { type: "item", label: "Shrink Selection", shortcut: "Shift+Alt+LeftArrow" },
  { type: "separator" },
  { type: "item", label: "Copy Line Up", shortcut: "Shift+Alt+UpArrow" },
  { type: "item", label: "Move Line Down", shortcut: "Shift+Alt+DownArrow" },
  { type: "item", label: "Move Line Up", shortcut: "Alt+UpArrow" },
  { type: "item", label: "Duplicate Selection", shortcut: "Alt+DownArrow" },
  { type: "separator" },
  { type: "item", label: "Add Cursor Above", shortcut: "Ctrl+Alt+UpArrow" },
  { type: "item", label: "Add Cursor Below", shortcut: "Ctrl+Alt+DownArrow" },
  { type: "separator" },
  { type: "item", label: "Add Cursor to Line Ends", shortcut: "Ctrl+Alt+L" },
  { type: "item", label: "Add Next Occurrence", shortcut: "Ctrl+D" },
  { type: "item", label: "Add Previous Occurrence" },
  { type: "item", label: "Select All Occurrence", shortcut: "Shift+Alt+L" },
  { type: "separator" },
  { type: "item", label: "Switch to Ctrl+Click for Multi-Cursor" },
  { type: "item", label: "Column Selection Mode" },
];

export const editMenuItems = [
  { type: "item", label: "Undo", shortcut: "Ctrl+Z" },
  { type: "item", label: "Redo", shortcut: "Ctrl+X" },
  { type: "item", label: "Cut", shortcut: "Ctrl+Shift+N" },
  { type: "item", label: "Copy", shortcut: "Ctrl+C" },
  { type: "item", label: "Paste", shortcut: "Ctrl+V" },
  { type: "separator" },
  { type: "item", label: "Find", shortcut: "Ctrl+F" },
  { type: "item", label: "Replace", shortcut: "Ctrl+H" },
  { type: "separator" },
  { type: "item", label: "Find in Files", shortcut: "Ctrl+Shift+F" },
  { type: "item", label: "Replace in Files", shortcut: "Ctrl+Shift+H" },
  { type: "separator" },
  { type: "item", label: "Toggle Line Comment", shortcut: "Ctrl+/" },
  { type: "item", label: "Toggle Block Comment", shortcut: "Shift+Alt+A" },
  { type: "item", label: "Emmet:Expand Abbreviation", shortcut: "Tab" },
];

export const fileMenuItems = [
  { type: "item", label: "New Text File", shortcut: "Ctrl+N" },
  { type: "item", label: "New File", shortcut: "Ctrl+Alt+Win+N" },
  { type: "item", label: "New Window", shortcut: "Ctrl+Shift+N" },
  { type: "separator" },
  { type: "item", label: "Open File", shortcut: "Ctrl+0" },
  { type: "item", label: "Open Folder", shortcut: "Ctrl+K Ctrl+0" },
  { type: "item", label: "Open Workspace from file..." },
  {
    type: "submenu",
    label: "Open Recent",
    children: [
      { type: "item", label: "Reopen closed editor" },
      { type: "separator" },
      { type: "item", label: "More" },
      { type: "item", label: "Clear Recently opened" },
    ],
  },
  { type: "item", label: "Add Folder to Workspace" },
  { type: "item", label: "Save Workspace As..." },
  { type: "item", label: "Duplicate Workspace" },
  { type: "separator" },
  { type: "item", label: "Save", shortcut: "Ctrl+S" },
  { type: "item", label: "Save As...", shortcut: "Ctrl+Shift+S" },
  { type: "item", label: "Save All", shortcut: "Ctrl+K S" },
  { type: "separator" },
  {
    type: "submenu",
    label: "Share",
    children: [
      { type: "item", label: "Export profile(default)..." },
      { type: "item", label: "Import Profile" },
    ],
  },
  { type: "separator" },
  { type: "item", label: "Auto Save" },
  {
    type: "submenu",
    label: "Preferences",
    children: [
      {
        type: "submenu",
        label: "Profiles(Default)",
        children: [
          { type: "item", label: "Default" },
          { type: "separator" },
          { type: "item", label: "Show Contents" },
          { type: "separator" },
          { type: "item", label: "Create Profile..." },
          { type: "item", label: "Delete Profile..." },
          { type: "separator" },
          { type: "item", label: "Export Profile..." },
          { type: "item", label: "Import Profile..." },
        ],
      },
      { type: "item", label: "Turn on Setting Sync..." },
      { type: "separator" },
      { type: "item", label: "Settings", shortcut: "Ctrl+K S" },
      { type: "item", label: "Extensions", shortcut: "Ctrl+Shift+X" },
      { type: "item", label: "Keyboard shortcuts", shortcut: "Ctrl+Shift+X" },
      { type: "item", label: "Configure user Snippets", shortcut: "Ctrl+Shift+X" },
      {
        type: "submenu",
        label: "Theme",
        children: [
          { type: "item", label: "Color Theme" },
          { type: "item", label: "File Icon Theme" },
          { type: "item", label: "Product Item Theme" },
        ],
      },
      { type: "item", label: "Online Service Settings", shortcut: "Ctrl+F4" },
    ],
  },
  { type: "separator" },
  { type: "item", label: "Revert File" },
  { type: "item", label: "Close Editor", shortcut: "Ctrl+F4" },
  { type: "item", label: "Close Folder", shortcut: "Ctrl+K F" },
  { type: "item", label: "Close Window", shortcut: "Alt+F4" },
  { type: "separator" },
  { type: "item", label: "Exit" },
];
